package com.plrs.domain.topic;

import com.plrs.domain.common.AuditFields;
import com.plrs.domain.common.DomainInvariantException;
import com.plrs.domain.common.DomainValidationException;
import java.util.Optional;

/**
 * Transient form of {@link Topic} prior to persistence. Carries everything
 * except the id — the repository's {@code save} method assigns the
 * {@code BIGSERIAL} id (§3.c.4) and returns a fully-populated {@link Topic}.
 *
 * <p>This split exists because a pre-persistence topic has no stable
 * identity: the surrogate key is generated by Postgres, not by the domain.
 * Exposing a draft type makes "not yet saved" a compile-time distinction
 * rather than a sentinel-id runtime check.
 *
 * <p>Validation mirrors {@link Topic}'s canonical constructor so a draft
 * that validates is guaranteed to produce a valid {@link Topic} once the
 * repository assigns an id. Field rules:
 *
 * <ul>
 *   <li>{@code name}, {@code parentTopicId}, {@code audit} must be non-null;
 *   <li>{@code name} trimmed is non-blank and 1..120 characters;
 *   <li>{@code description}, when present, is at most 500 characters.
 * </ul>
 *
 * <p>Traces to: §3.c.1.3 (topics DDL), §3.c.4 (BIGSERIAL surrogate), FR-07.
 */
public record TopicDraft(
        String name, String description, Optional<TopicId> parentTopicId, AuditFields audit) {

    public TopicDraft {
        if (name == null) {
            throw new DomainValidationException("TopicDraft name must not be null");
        }
        if (parentTopicId == null) {
            throw new DomainValidationException(
                    "TopicDraft parentTopicId must not be null"
                            + " (use Optional.empty() for a root topic)");
        }
        if (audit == null) {
            throw new DomainValidationException("TopicDraft audit must not be null");
        }
        String trimmed = name.trim();
        if (trimmed.isEmpty()) {
            throw new DomainInvariantException("TopicDraft name must not be blank");
        }
        if (trimmed.length() > Topic.MAX_NAME_LENGTH) {
            throw new DomainInvariantException(
                    "TopicDraft name must be at most " + Topic.MAX_NAME_LENGTH
                            + " characters, got " + trimmed.length());
        }
        if (description != null && description.length() > Topic.MAX_DESCRIPTION_LENGTH) {
            throw new DomainValidationException(
                    "TopicDraft description must be at most " + Topic.MAX_DESCRIPTION_LENGTH
                            + " characters, got " + description.length());
        }
        name = trimmed;
    }
}
