-- Traces to: FR-04 (password reset with token, 30-min expiry).
--
-- Two columns on users plus a partial unique index that enforces
-- "at most one active reset token per user" (the column WHERE clause
-- excludes expired tokens automatically). The token itself is a
-- 32-char random string generated by RequestPasswordResetUseCase.

ALTER TABLE plrs_ops.users
  ADD COLUMN reset_token       VARCHAR(80),
  ADD COLUMN reset_expires_at  TIMESTAMPTZ;

-- Partial index for fast token lookup. Cannot reference NOW() in the
-- predicate (Postgres requires immutable functions in index
-- predicates); the use case enforces the 30-min expiry in code
-- instead. Stale tokens stay in the column until clearResetToken or
-- the next reset request overwrites them — harmless because
-- findByResetToken's caller checks expiry before honouring the token.
CREATE INDEX idx_users_reset_token
  ON plrs_ops.users (reset_token)
  WHERE reset_token IS NOT NULL;

COMMENT ON COLUMN plrs_ops.users.reset_token IS
  '32-char URL-safe random token; cleared on confirm or expiry.';
COMMENT ON COLUMN plrs_ops.users.reset_expires_at IS
  'UTC expiry timestamp; ConfirmPasswordReset rejects after this instant.';
