#!/usr/bin/env bash
# Regenerates plrs-full-regression.postman_collection.json by wrapping
# the four per-iteration collections inside a single collection with
# four folders. Re-run this whenever a per-iter collection changes.
#
# Why generate instead of hand-maintain: hand-copying the items from
# four collections drifts immediately. Generating means the per-iter
# Newman runs and the consolidated regression always test the same
# requests and assertions.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/plrs-full-regression.postman_collection.json"

jq -n \
  --slurpfile i1 "$DIR/plrs-iter1.postman_collection.json" \
  --slurpfile i2 "$DIR/plrs-iter2.postman_collection.json" \
  --slurpfile i3 "$DIR/plrs-iter3.postman_collection.json" \
  --slurpfile i4 "$DIR/plrs-iter4.postman_collection.json" \
  '{
    info: {
      name: "PLRS Full Regression",
      description: "Consolidated regression: every Iter 1..4 Newman flow, run as one Newman invocation. Generated by test/newman/build-full-regression.sh — do not hand-edit. Requires test/newman/seed-full.sql to be loaded first (combines all per-iter seed SQLs).",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    item: [
      { name: "Iter 1 — register / login / me / logout",         item: $i1[0].item },
      { name: "Iter 2 — instructor catalog + interactions",       item: $i2[0].item },
      { name: "Iter 3 — recommendations + offline eval",          item: $i3[0].item },
      { name: "Iter 4 — paths, CSV, lockout, admin tunables",     item: $i4[0].item }
    ]
  }' > "$OUT"

echo "wrote $OUT"
echo "  folders: 4"
echo "  total requests: $(jq '[.. | objects | select(has("request")) ] | length' "$OUT")"
